# Generated by Django 2.2.6 on 2019-10-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_contact_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REPORT_NUM', models.IntegerField(default=0)),
                ('EVENT_PROPERTY_NAME', models.CharField(max_length=200)),
                ('EVENT_TYPE_ID', models.IntegerField(default=0)),
                ('EVENT_TYPE_NAME', models.CharField(max_length=200)),
                ('EVENT_SRC_NAME', models.CharField(max_length=200)),
                ('DISTRICT_ID', models.IntegerField(default=0)),
                ('INTIME_ARCHIVE_NUM', models.IntegerField(default=0)),
                ('SUB_TYPE_ID', models.IntegerField(default=0)),
                ('DISTRICT_NAME', models.CharField(max_length=200)),
                ('COMMUNITY_ID', models.IntegerField(default=0)),
                ('REC_ID', models.IntegerField(default=0)),
                ('STREET_ID', models.IntegerField(default=0)),
                ('OVERTIME_ARCHIVE_NUM', models.IntegerField(default=0)),
                ('OPERATE_NUM', models.IntegerField(default=0)),
                ('DISPOSE_UNIT_ID', models.IntegerField(default=0)),
                ('STREET_NAME', models.CharField(max_length=200)),
                ('CREATE_TIME', models.IntegerField(default=0)),
                ('EVENT_SRC_ID', models.IntegerField(default=0)),
                ('INTIME_TO_ARCHIVE_NUM', models.IntegerField(default=0)),
                ('SUB_TYPE_NAME', models.CharField(max_length=200)),
                ('EVENT_PROPERTY_ID', models.IntegerField(default=0)),
                ('OCCUR_PLACE', models.CharField(max_length=200)),
                ('COMMUNITY_NAME', models.CharField(max_length=200)),
                ('DISPOSE_UNIT_NAME', models.CharField(max_length=200)),
                ('MAIN_TYPE_NAME', models.CharField(max_length=200)),
                ('MAIN_TYPE_ID', models.IntegerField(default=0)),
            ],
        ),
    ]
