# Generated by Django 2.2.6 on 2019-10-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dic',
            name='COMMUNITY_ID',
            field=models.CharField(max_length=200),
        ),
    ]
