# Generated by Django 2.2.6 on 2019-10-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_auto_20191025_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dic',
            name='COMMUNITY_ID',
            field=models.IntegerField(default=0),
        ),
    ]
