# Generated by Django 2.2.6 on 2019-10-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0012_auto_20191026_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
