# Generated by Django 2.2.6 on 2019-10-26 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0014_auto_20191026_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='numm',
        ),
    ]
