# Generated by Django 2.2.6 on 2019-10-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0015_remove_test_numm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='num',
        ),
    ]
