# Generated by Django 2.2.6 on 2019-10-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0023_dic_testtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('userkeyword', models.CharField(max_length=200)),
                ('userdepart', models.CharField(max_length=200)),
            ],
        ),
    ]
