# Generated by Django 2.2.6 on 2019-11-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0032_sysclock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysclock',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
