# Generated by Django 2.2.6 on 2019-11-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0033_auto_20191106_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysclock',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
