# Generated by Django 2.2.5 on 2019-12-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0036_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=128)),
                ('staff_verification', models.CharField(max_length=128)),
                ('staff_username', models.CharField(max_length=128)),
            ],
        ),
    ]
