# Generated by Django 2.2.6 on 2019-12-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0038_auto_20191205_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='realclock',
        ),
    ]
